import {
  LayoutDashboard,
  Users,
  BarChart3,
  Settings,
  CreditCard,
  FileText,
  Bell,
  Shield,
  Blocks,
  Layers,
  KanbanSquare,
  MessageSquare,
  Inbox,
  Sparkles,
  Activity,
  Shapes,
  BarChart2,
  Loader2,
  Code2,
  Home,
  Info,
  Tag,
  Mail,
  Clock,
  Wrench,
  AlertTriangle,
  CalendarDays,
  ShoppingBag,
  Newspaper,
  Receipt,
  BookUser,
} from "lucide-react"
import type { NavGroup } from "@/types"

export const NAV_GROUPS: NavGroup[] = [
  {
    label: "Dashboard",
    items: [
      { icon: LayoutDashboard, title: "Default", href: "/dashboard" },
      { icon: BarChart3, title: "Analytics", href: "/dashboard/analytics" },
      { icon: Users, title: "CRM", href: "/dashboard/crm" },
      { icon: FileText, title: "Blog", href: "/dashboard/blog" },
    ],
  },
  {
    label: "Management",
    items: [
      { icon: Users, title: "Users", children: [
        { title: "List",    href: "/users/list"    },
        { title: "Cards",   href: "/users/cards"   },
        { title: "Details", href: "/users/details" },
        { title: "Profile", href: "/users/profile" },
      ]},
      { icon: KanbanSquare, title: "Kanban", children: [
        { title: "Board",   href: "/kanban/board"   },
        { title: "Backlog", href: "/kanban/backlog"  },
        { title: "List",    href: "/kanban/list"     },
      ]},
      { icon: BookUser, title: "Contact", children: [
        { title: "List", href: "/contact/list" },
        { title: "Card", href: "/contact/card" },
      ]},
      { icon: MessageSquare, title: "Chat", href: "/chat" },
      { icon: CalendarDays, title: "Calendar", href: "/calendar" },
      { icon: Inbox, title: "Mail", children: [
        { title: "Inbox", href: "/mail/inbox" },
        { title: "List",  href: "/mail/list"  },
      ]},
      { icon: FileText, title: "Reports", href: "/reports" },
      { icon: Bell, title: "Notifications", href: "/notifications" },
      { icon: ShoppingBag, title: "E-Commerce", children: [
        { title: "Products",        href: "/ecommerce/products"        },
        { title: "Product Details", href: "/ecommerce/product-details" },
        { title: "Product List",    href: "/ecommerce/product-list"    },
        { title: "Checkout",        href: "/ecommerce/checkout"        },
      ]},
      { icon: Newspaper, title: "Blog", children: [
        { title: "Add New",      href: "/blog/new"     },
        { title: "Edit",         href: "/blog/edit"    },
        { title: "Blog List",    href: "/blog/list"    },
        { title: "Blog Details", href: "/blog/details" },
      ]},
      { icon: Receipt, title: "Invoice", children: [
        { title: "Create",   href: "/invoice/create"  },
        { title: "List",     href: "/invoice/list"    },
        { title: "Edit",     href: "/invoice/edit"    },
        { title: "Details",  href: "/invoice/details" },
        { title: "Client",        href: "/invoice/client"        },
        { title: "Client Create", href: "/invoice/client/create" },
        { title: "Items",         href: "/invoice/items"          },
        { title: "Add Item",      href: "/invoice/items/add-item" },
        { title: "Payment", children: [
          { title: "List",    href: "/invoice/payment"         },
          { title: "Create",  href: "/invoice/payment/create"  },
          { title: "Details", href: "/invoice/payment/details" },
        ]},
      ]},
    ],
  },
  {
    label: "Account",
    items: [
      { icon: CreditCard, title: "Pricing", href: "/pricing" },
      { icon: Activity, title: "Activity", href: "/activity" },
      { icon: Shield, title: "Security", href: "/security" },
      { icon: Settings, title: "Settings", href: "/settings" },
    ],
  },
  {
    label: "UI Elements",
    items: [
      { icon: Shapes, title: "Icons", children: [
        { title: "Default", href: "/icons/default" },
        { title: "Brands", href: "/icons/brands" },
      ]},
      { icon: BarChart2, title: "Charts",  href: "/charts"  },
      { icon: Loader2,   title: "Loaders", href: "/loaders" },
      {
        icon: Layers,
        title: "Forms",
        children: [
          { title: "Login", href: "/forms/login" },
          { title: "Register", href: "/forms/register" },
          { title: "Forgot Password", href: "/forms/forgot-password" },
          { title: "Contact", href: "/forms/contact" },
          { title: "Profile", href: "/forms/profile" },
          { title: "Payment", href: "/forms/payment" },
          { title: "Multi Step", href: "/forms/multi-step" },
          { title: "Validation", href: "/forms/validation" },
        ],
      },
      {
        icon: Code2,
        title: "Basic",
        children: [
          { title: "Typography",  href: "/basic/typography"  },
          { title: "Table",       href: "/basic/table"       },
          { title: "List",        href: "/basic/list"        },
          { title: "Colors",      href: "/basic/colors"      },
          { title: "Blockquote",  href: "/basic/blockquote"  },
          { title: "Images",      href: "/basic/images"      },
        ],
      },
      {
        icon: Blocks,
        title: "Components",
        children: [
          { title: "Accordion", href: "/components/accordion" },
          { title: "Alert", href: "/components/alert" },
          { title: "Alert Dialog", href: "/components/alert-dialog" },
          { title: "Aspect Ratio", href: "/components/aspect-ratio" },
          { title: "Avatar", href: "/components/avatar" },
          { title: "Badge", href: "/components/badge" },
          { title: "Breadcrumb", href: "/components/breadcrumb" },
          { title: "Button", href: "/components/button" },
          { title: "Button Group", href: "/components/button-group" },
          { title: "Calendar", href: "/components/calendar" },
          { title: "Card", href: "/components/card" },
          { title: "Carousel", href: "/components/carousel" },
          { title: "Chart", href: "/components/chart" },
          { title: "Checkbox", href: "/components/checkbox" },
          { title: "Collapsible", href: "/components/collapsible" },
          { title: "Combobox", href: "/components/combobox" },
          { title: "Command", href: "/components/command" },
          { title: "Context Menu", href: "/components/context-menu" },
          { title: "Data Table", href: "/components/data-table" },
          { title: "Date Picker", href: "/components/date-picker" },
          { title: "Dialog", href: "/components/dialog" },
          { title: "Drawer", href: "/components/drawer" },
          { title: "Dropdown Menu", href: "/components/dropdown-menu" },
          { title: "Empty", href: "/components/empty" },
          { title: "Field", href: "/components/field" },
          { title: "Form", href: "/components/form" },
          { title: "Hover Card", href: "/components/hover-card" },
          { title: "Input", href: "/components/input" },
          { title: "Input Group", href: "/components/input-group" },
          { title: "Input OTP", href: "/components/input-otp" },
          { title: "Item", href: "/components/item" },
          { title: "Kbd", href: "/components/kbd" },
          { title: "Label", href: "/components/label" },
          { title: "Menubar", href: "/components/menubar" },
          { title: "Navigation Menu", href: "/components/navigation-menu" },
          { title: "Native Select", href: "/components/native-select" },
          { title: "Pagination", href: "/components/pagination" },
          { title: "Popover", href: "/components/popover" },
          { title: "Progress", href: "/components/progress" },
          { title: "Radio Group", href: "/components/radio-group" },
          { title: "Resizable", href: "/components/resizable" },
          { title: "Scroll Area", href: "/components/scroll-area" },
          { title: "Select", href: "/components/select" },
          { title: "Separator", href: "/components/separator" },
          { title: "Sheet", href: "/components/sheet" },
          { title: "Skeleton", href: "/components/skeleton" },
          { title: "Slider", href: "/components/slider" },
          { title: "Sonner", href: "/components/sonner" },
          { title: "Spinner", href: "/components/spinner" },
          { title: "Switch", href: "/components/switch" },
          { title: "Table", href: "/components/table" },
          { title: "Tabs", href: "/components/tabs" },
          { title: "Textarea", href: "/components/textarea" },
          { title: "Toggle", href: "/components/toggle" },
          { title: "Toggle Group", href: "/components/toggle-group" },
          { title: "Tooltip", href: "/components/tooltip" },
          { title: "Typography", href: "/components/typography" },
        ],
      },
      {
        icon: Sparkles,
        title: "Advanced",
        children: [
          { title: "Editor",        href: "/advanced/editor"        },
          { title: "File Uploader", href: "/advanced/file-uploader" },
          { title: "Image Cropper", href: "/advanced/image-cropper" },
        ],
      },
    ],
  },
  {
    label: "Landing Pages",
    items: [
      { icon: Home,    title: "Home",         href: "/landing/home"         },
      { icon: Info,    title: "About",        href: "/landing/about"        },
      { icon: Tag,     title: "Pricing",      href: "/landing/pricing"      },
      { icon: Mail,    title: "Contact",      href: "/landing/contact"      },
      { icon: Clock,   title: "Coming Soon",  href: "/landing/coming-soon"  },
      { icon: Wrench,        title: "Maintenance",  href: "/landing/maintenance"  },
      {
        icon: AlertTriangle,
        title: "Error Pages",
        children: [
          { title: "404 — Not Found",    href: "/landing/error/404" },
          { title: "500 — Server Error", href: "/landing/error/500" },
          { title: "401 — Unauthorized", href: "/landing/error/401" },
        ],
      },
    ],
  },
]

export const APP_NAME = "Next SaaS"
