import {
  LayoutDashboard,
  Users,
  BarChart3,
  Settings,
  CreditCard,
  FileText,
  Bell,
  Shield,
  Blocks,
  Layers,
} from "lucide-react"
import type { NavGroup } from "@/types"

export const NAV_GROUPS: NavGroup[] = [
  {
    label: "Overview",
    items: [
      { icon: LayoutDashboard, title: "Dashboard", href: "/dashboard" },
      { icon: BarChart3, title: "Analytics", href: "/analytics" },
    ],
  },
  {
    label: "Management",
    items: [
      { icon: Users, title: "Users", href: "/users", badge: "24" },
      { icon: FileText, title: "Reports", href: "/reports" },
      { icon: Bell, title: "Notifications", href: "/notifications" },
    ],
  },
  {
    label: "Account",
    items: [
      { icon: CreditCard, title: "Billing", href: "/billing" },
      { icon: Shield, title: "Security", href: "/security" },
      { icon: Settings, title: "Settings", href: "/settings" },
    ],
  },
  {
    label: "Developer",
    items: [
      {
        icon: Layers,
        title: "Forms",
        children: [
          { title: "Login", href: "/forms/login" },
          { title: "Register", href: "/forms/register" },
          { title: "Forgot Password", href: "/forms/forgot-password" },
          { title: "Contact", href: "/forms/contact" },
          { title: "Profile", href: "/forms/profile" },
          { title: "Payment", href: "/forms/payment" },
          { title: "Multi Step", href: "/forms/multi-step" },
        ],
      },
      {
        icon: Blocks,
        title: "Components",
        children: [
          { title: "Accordion", href: "/components/accordion" },
          { title: "Alert", href: "/components/alert" },
          { title: "Alert Dialog", href: "/components/alert-dialog" },
          { title: "Aspect Ratio", href: "/components/aspect-ratio" },
          { title: "Avatar", href: "/components/avatar" },
          { title: "Badge", href: "/components/badge" },
          { title: "Breadcrumb", href: "/components/breadcrumb" },
          { title: "Button", href: "/components/button" },
          { title: "Button Group", href: "/components/button-group" },
          { title: "Calendar", href: "/components/calendar" },
          { title: "Card", href: "/components/card" },
          { title: "Carousel", href: "/components/carousel" },
          { title: "Chart", href: "/components/chart" },
          { title: "Checkbox", href: "/components/checkbox" },
          { title: "Collapsible", href: "/components/collapsible" },
          { title: "Combobox", href: "/components/combobox" },
          { title: "Command", href: "/components/command" },
          { title: "Context Menu", href: "/components/context-menu" },
          { title: "Date Picker", href: "/components/date-picker" },
          { title: "Dialog", href: "/components/dialog" },
          { title: "Drawer", href: "/components/drawer" },
          { title: "Dropdown Menu", href: "/components/dropdown-menu" },
          { title: "Empty", href: "/components/empty" },
          { title: "Field", href: "/components/field" },
          { title: "Form", href: "/components/form" },
          { title: "Hover Card", href: "/components/hover-card" },
          { title: "Input", href: "/components/input" },
          { title: "Input Group", href: "/components/input-group" },
          { title: "Input OTP", href: "/components/input-otp" },
          { title: "Item", href: "/components/item" },
          { title: "Kbd", href: "/components/kbd" },
          { title: "Label", href: "/components/label" },
          { title: "Menubar", href: "/components/menubar" },
          { title: "Navigation Menu", href: "/components/navigation-menu" },
          { title: "Native Select", href: "/components/native-select" },
          { title: "Pagination", href: "/components/pagination" },
          { title: "Popover", href: "/components/popover" },
          { title: "Progress", href: "/components/progress" },
          { title: "Radio Group", href: "/components/radio-group" },
          { title: "Resizable", href: "/components/resizable" },
          { title: "Scroll Area", href: "/components/scroll-area" },
          { title: "Select", href: "/components/select" },
          { title: "Separator", href: "/components/separator" },
          { title: "Sheet", href: "/components/sheet" },
          { title: "Skeleton", href: "/components/skeleton" },
          { title: "Slider", href: "/components/slider" },
          { title: "Sonner", href: "/components/sonner" },
          { title: "Spinner", href: "/components/spinner" },
          { title: "Switch", href: "/components/switch" },
          { title: "Table", href: "/components/table" },
          { title: "Tabs", href: "/components/tabs" },
          { title: "Textarea", href: "/components/textarea" },
          { title: "Toggle", href: "/components/toggle" },
          { title: "Toggle Group", href: "/components/toggle-group" },
          { title: "Tooltip", href: "/components/tooltip" },
          { title: "Typography", href: "/components/typography" },
        ],
      },
    ],
  },
]

export const APP_NAME = "Next SaaS"
